services:
  db:
    image: postgres:16-alpine
    container_name: finanzas_db
    environment:
      POSTGRES_USER: vicente
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: finanzas
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build: .
    container_name: fintrack_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
volumes:
  db_data:
